// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwTQZoWlwmuXkM9uyWZSi_WzjMEVYTOsY',
    appId: '1:174981238450:web:84a6cbcb2309bc89b243ab',
    messagingSenderId: '174981238450',
    projectId: 'snakegameman',
    authDomain: 'snakegameman.firebaseapp.com',
    storageBucket: 'snakegameman.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbfMo1rcrWo8fO0FtAKn_fLLv61ktn3Ds',
    appId: '1:174981238450:android:d83500ad5bfd37f4b243ab',
    messagingSenderId: '174981238450',
    projectId: 'snakegameman',
    storageBucket: 'snakegameman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8T_ACUJTJKGwLy0LYzMl-r_GrZ4bum5s',
    appId: '1:174981238450:ios:8f546174d8a37371b243ab',
    messagingSenderId: '174981238450',
    projectId: 'snakegameman',
    storageBucket: 'snakegameman.appspot.com',
    iosClientId: '174981238450-v2h9fhjr1qs4vg27tugicvbuj61olmu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.snake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8T_ACUJTJKGwLy0LYzMl-r_GrZ4bum5s',
    appId: '1:174981238450:ios:8f546174d8a37371b243ab',
    messagingSenderId: '174981238450',
    projectId: 'snakegameman',
    storageBucket: 'snakegameman.appspot.com',
    iosClientId: '174981238450-v2h9fhjr1qs4vg27tugicvbuj61olmu3.apps.googleusercontent.com',
    iosBundleId: 'com.example.snake',
  );
}
